### ISSUE TITLE
Error opening inr files

### ISSUE THREAD

**Issue by kapoorlab** [leoguignard/IO#2]
Hi,

I ran into an issue when trying to open inr.gz file with imread, as an example, this minimal code would reproduce the issue:

from IO import imread as inrimread 
inrimread(Astec-Pm11_fuse_t060.inr.gz)

throws an error

~/LightSheetTrain/LocalIO/inrimage.py in read_inrimage(filename)
    137     size = ntyp.itemsize * xdim * ydim * zdim * vdim
    138     #print(size,f.read(size), ntyp.itemsize, xdim, ydim, zdim, vdim)
--> 139     mat = np.fromstring(f.read(size).decode('latin-1'),ntyp)
    140     if vdim != 1 :
    141         mat = mat.reshape( (vdim,xdim,ydim,zdim), order="F" )
AttributeError: 'str' object has no attribute 'decode'

I tried removing the decode bit of the code as it seems the string is already decoded but then got another error saying that mat is of size 0. I can't figure out whats going wrong here.

**Comment by leoguignard** [comment]
Thanks for the feedback, it came from the difference between bytes and strings that was introduced when switching from python 2 to 3. (I haven't used inr files since then ...)
It should be fixed now.
